Update AdGuardHome rules.yml

diff --git a/.github/workflows/AdGuardHome rules.yml b/.github/workflows/AdGuardHome rules.yml
--- a/.github/workflows/AdGuardHome rules.yml
+++ b/.github/workflows/AdGuardHome rules.yml
@@ -25,7 +25,7 @@ jobs:
 
           urls=(
             "https://raw.githubusercontent.com/wxglenovo/AdGuardHome-Filter/main/Create%20a%20Custom%20AdGuard%20Home%20Filtering%20Rule.txt"
-            "https://gh-proxy.com/raw.githubusercontent.com/changzhaoCZ/fqnovel-adrules/refs/heads/main/fqnovel-fxxk_ads"
+            "https://gh-proxy.com/raw.githubusercontent.com/changzhaoCZ/fqnovel-adrules/main/fqnovel-fxxk_ads"
             "https://anti-ad.net/easylist.txt"
             "https://raw.githubusercontent.com/REIJI007/Adblock-Rule-Collection/main/ADBLOCK_RULE_COLLECTION_DNS.txt"
             "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt"
@@ -36,17 +36,14 @@ jobs:
             "https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/skyrules.txt"
             "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt"
             "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt"
-            "https://raw.githubusercontent.com/wxglenovo/Shadowrocket-to-AdGuard-Home/refs/heads/main/AdGuardHome.txt"            
+            "https://raw.githubusercontent.com/wxglenovo/Shadowrocket-to-AdGuard-Home/main/AdGuardHome.txt"            
           )
 
           echo "📥 开始下载并合并所有规则..."
           for url in "${urls[@]}"; do
             echo "Downloading $url"
-            if curl -sSL --retry 3 --fail "$url" >> tmp/all_raw.txt; then
-              echo "" >> tmp/all_raw.txt
-            else
-              echo "⚠️ Failed to download $url, skipped"
-            fi
+            curl -sSL --retry 3 --fail "$url" >> tmp/all_raw.txt || echo "⚠️ Failed to download $url, skipped"
+            echo "" >> tmp/all_raw.txt
           done
 
           echo "🧹 清理注释、空行，同时删除无用规则..."
